import type { PresetConfig } from '@/lib/moduleDefinitions'

export const PRESETS: readonly PresetConfig[] = [
  {
    name: 'Neofetch',
    description: 'Classic neofetch-style layout with common system info',
    globalSettings: {
      logo: { source: 'none', type: 'auto', padding: { top: 0, left: 0, right: 0 } },
      display: { separator: ': ', color: 'cyan', brightColor: true },
    },
    modules: [
      { type: 'title' },
      { type: 'separator' },
      { type: 'os' },
      { type: 'kernel' },
      { type: 'uptime' },
      { type: 'packages' },
      { type: 'shell' },
      { type: 'terminal' },
      { type: 'wm' },
      { type: 'cpu' },
      { type: 'gpu' },
      { type: 'memory' },
      { type: 'colors' },
    ],
  },
  {
    name: 'Minimal',
    description: 'Bare essentials — OS, kernel, shell, and uptime',
    globalSettings: {
      logo: { source: 'none' },
      display: { separator: ' → ', color: 'green', brightColor: false },
    },
    modules: [
      { type: 'os' },
      { type: 'kernel' },
      { type: 'shell' },
      { type: 'uptime' },
    ],
  },
  {
    name: 'Hardware',
    description: 'Detailed hardware info with temperatures and driver versions',
    globalSettings: {
      logo: { source: 'none', type: 'auto', padding: { top: 0, left: 0, right: 0 } },
      display: { separator: ': ', color: 'yellow', brightColor: true, keyWidth: 12 },
    },
    modules: [
      { type: 'title' },
      { type: 'separator' },
      { type: 'cpu', options: { temp: true, showPeCoreCount: true, freqNdig: 2 } },
      { type: 'cpuusage' },
      { type: 'gpu', options: { temp: true, driverVersion: true } },
      { type: 'memory' },
      { type: 'swap' },
      { type: 'disk', options: { folders: '/' } },
      { type: 'battery' },
      { type: 'display', options: { compactType: 'original' } },
      { type: 'brightness' },
    ],
  },
  {
    name: 'Developer',
    description: 'Developer-focused with shell, terminal, packages, and network',
    globalSettings: {
      logo: { source: 'none' },
      display: { separator: '  ', color: 'magenta', brightColor: true },
    },
    modules: [
      { type: 'title' },
      { type: 'separator' },
      { type: 'os' },
      { type: 'kernel' },
      { type: 'shell' },
      { type: 'terminal' },
      { type: 'packages' },
      { type: 'cpu' },
      { type: 'memory' },
      { type: 'disk' },
      { type: 'localip', options: { compact: true } },
      { type: 'wifi' },
      { type: 'colors' },
    ],
  },
  {
    name: 'Paleofetch',
    description: 'Paleofetch-inspired minimal output with muted colors',
    globalSettings: {
      logo: { source: 'none' },
      display: { separator: ' ~ ', color: 'blue', brightColor: false },
    },
    modules: [
      { type: 'os' },
      { type: 'kernel' },
      { type: 'uptime' },
      { type: 'shell' },
      { type: 'wm' },
      { type: 'memory' },
      { type: 'cpu' },
      { type: 'colors' },
    ],
  },
  {
    name: 'Server',
    description: 'Server monitoring — hardware, network, storage, and load',
    globalSettings: {
      logo: { source: 'none' },
      display: { separator: ': ', color: 'red', brightColor: true, keyWidth: 14 },
    },
    modules: [
      { type: 'title' },
      { type: 'separator' },
      { type: 'os' },
      { type: 'kernel' },
      { type: 'initsystem' },
      { type: 'uptime' },
      { type: 'loadavg' },
      { type: 'cpu', options: { temp: true } },
      { type: 'cpuusage' },
      { type: 'memory' },
      { type: 'swap' },
      { type: 'disk', options: { folders: '/' } },
      { type: 'diskio' },
      { type: 'localip' },
      { type: 'publicip' },
      { type: 'netio' },
      { type: 'dns' },
      { type: 'processes' },
      { type: 'users' },
    ],
  },
  {
    name: 'Desktop',
    description: 'Full desktop environment — display, theming, fonts, and peripherals',
    globalSettings: {
      logo: { source: 'none' },
      display: { separator: '  ', color: 'brightCyan', brightColor: false },
    },
    modules: [
      { type: 'title' },
      { type: 'separator' },
      { type: 'os' },
      { type: 'de' },
      { type: 'wm' },
      { type: 'wmtheme' },
      { type: 'theme' },
      { type: 'icons' },
      { type: 'font' },
      { type: 'cursor' },
      { type: 'wallpaper' },
      { type: 'break' },
      { type: 'terminal' },
      { type: 'terminalfont' },
      { type: 'terminalsize' },
      { type: 'shell' },
      { type: 'editor' },
      { type: 'break' },
      { type: 'display', options: { compactType: 'original' } },
      { type: 'monitor' },
      { type: 'brightness' },
      { type: 'sound' },
      { type: 'break' },
      { type: 'colors' },
    ],
  },
  {
    name: 'Laptop',
    description: 'Laptop-focused — battery, WiFi, Bluetooth, peripherals, and power',
    globalSettings: {
      logo: { source: 'none' },
      display: { separator: ': ', color: 'green', brightColor: true },
    },
    modules: [
      { type: 'title' },
      { type: 'separator' },
      { type: 'os' },
      { type: 'host' },
      { type: 'kernel' },
      { type: 'uptime' },
      { type: 'battery' },
      { type: 'poweradapter' },
      { type: 'break' },
      { type: 'cpu', options: { temp: true } },
      { type: 'gpu', options: { temp: true } },
      { type: 'memory' },
      { type: 'disk', options: { folders: '/' } },
      { type: 'break' },
      { type: 'display', options: { compactType: 'original' } },
      { type: 'brightness' },
      { type: 'wifi' },
      { type: 'bluetooth' },
      { type: 'camera' },
      { type: 'keyboard' },
      { type: 'sound' },
      { type: 'break' },
      { type: 'colors' },
    ],
  },
  {
    name: 'Everything',
    description: 'Comprehensive — every major module for full system inventory',
    globalSettings: {
      logo: { source: 'none' },
      display: { separator: ': ', color: 'yellow', brightColor: true, keyWidth: 16 },
    },
    modules: [
      { type: 'title' },
      { type: 'separator' },
      { type: 'os' },
      { type: 'host' },
      { type: 'kernel' },
      { type: 'initsystem' },
      { type: 'uptime' },
      { type: 'loadavg' },
      { type: 'processes' },
      { type: 'packages' },
      { type: 'users' },
      { type: 'break' },
      { type: 'cpu', options: { temp: true, showPeCoreCount: true } },
      { type: 'cpucache' },
      { type: 'cpuusage' },
      { type: 'gpu', options: { temp: true, driverVersion: true } },
      { type: 'opengl' },
      { type: 'opencl' },
      { type: 'vulkan' },
      { type: 'break' },
      { type: 'memory' },
      { type: 'physicalmemory' },
      { type: 'swap' },
      { type: 'disk', options: { folders: '/' } },
      { type: 'physicaldisk' },
      { type: 'diskio' },
      { type: 'break' },
      { type: 'shell' },
      { type: 'terminal' },
      { type: 'terminalfont' },
      { type: 'editor' },
      { type: 'de' },
      { type: 'wm' },
      { type: 'wmtheme' },
      { type: 'theme' },
      { type: 'icons' },
      { type: 'font' },
      { type: 'cursor' },
      { type: 'wallpaper' },
      { type: 'break' },
      { type: 'display', options: { compactType: 'original' } },
      { type: 'monitor' },
      { type: 'brightness' },
      { type: 'sound' },
      { type: 'player' },
      { type: 'media' },
      { type: 'break' },
      { type: 'localip' },
      { type: 'publicip' },
      { type: 'wifi' },
      { type: 'dns' },
      { type: 'bluetooth' },
      { type: 'netio' },
      { type: 'break' },
      { type: 'bios' },
      { type: 'board' },
      { type: 'chassis' },
      { type: 'tpm' },
      { type: 'battery' },
      { type: 'poweradapter' },
      { type: 'datetime' },
      { type: 'locale' },
      { type: 'weather' },
      { type: 'break' },
      { type: 'version' },
      { type: 'colors' },
    ],
  },
] as const
